/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalContextMenu: typeof import('./src/components/GlobalContextMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    SponsorModal: typeof import('./src/components/SponsorModal.vue')['default']
    StartModal: typeof import('./src/components/StartModal.vue')['default']
    TournamentModal: typeof import('./src/components/TournamentModal.vue')['default']
    UApp: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorPicker: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UContextMenu: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFileUpload: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPopover: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USidebar: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Sidebar.vue')['default']
    UStepper: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue')['default']
    UTable: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTextarea: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../../../node_modules/.bun/@nuxt+ui@4.11.0+3effab2cb3b59291/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
